### PR TITLE
Destroy resize event on teardown

### PR DESCRIPTION
**Pull request by jornbakhuys**
The resize event wasn't destroyed, so it showed errors after teardown.

### CODE REVIEW

**Comment by giuseppeg** [comment]
`off` seems to be working here http://jsfiddle.net/ZDB5R/1/
Do you have a testcase?

[edit] sorry you were right, I don't think that using a namespaced event is the best way to solve it though. I'll look into this asap

**Comment by giuseppeg** [comment]
What you can do here is unbinding using the callback 
ie. add 

``` javascript
elem.off("resize", jqre.poll);
```

at the bottom of `teardown` http://jsfiddle.net/f3S8t/
Please let me know if you want to fix this. Thank you :)

**Comment by jornbakhuys** [comment]
Agreed, pull request has been updated.

**Comment by giuseppeg** [comment]
Awesome, thank you!
Can you make a new branch & pull-request with the new fix only? I will close this.

**Pull request closed without merging**
